# Managed by setup_new_machine.sh.
keys:
  admins:
    - age1c9xuldm8rxssv00a0y9zav0fcjzujtqgtv2t0gkk4anutvuz3s3qry70pm
    - age1revy59xnwzqfukcukjqcu76kz7vflmncme4h4gykw7afv8wz4gvsydm3sp
  hosts:
    - fqdn: eager-whale.dome.ms
      age: age1nhpwa7zxe9sjuh5uvc4c9llcvr5kc9gyymrljl2wjl4zh3rqefeqsnyjj0
      path_regex: 'hosts/ms/dome/eager-whale/secrets/[^/]+\.yaml$'
    - fqdn: happy-owl.dome.ms
      age: age1ud74hwzecx9tk2wk07l232tdd63hkcx58w7u0dq7f0r5748s4f5qvuw3cg
      path_regex: 'hosts/ms/dome/happy-owl/secrets/[^/]+\.yaml$'
creation_rules:
  - path_regex: 'secrets/cluster\.yaml$'
    key_groups:
      - age:
        - age1c9xuldm8rxssv00a0y9zav0fcjzujtqgtv2t0gkk4anutvuz3s3qry70pm
        - age1revy59xnwzqfukcukjqcu76kz7vflmncme4h4gykw7afv8wz4gvsydm3sp
        - age1nhpwa7zxe9sjuh5uvc4c9llcvr5kc9gyymrljl2wjl4zh3rqefeqsnyjj0
        - age1ud74hwzecx9tk2wk07l232tdd63hkcx58w7u0dq7f0r5748s4f5qvuw3cg
  - path_regex: 'hosts/ms/dome/eager-whale/secrets/[^/]+\.yaml$'
    key_groups:
      - age:
        - age1c9xuldm8rxssv00a0y9zav0fcjzujtqgtv2t0gkk4anutvuz3s3qry70pm
        - age1revy59xnwzqfukcukjqcu76kz7vflmncme4h4gykw7afv8wz4gvsydm3sp
        - age1nhpwa7zxe9sjuh5uvc4c9llcvr5kc9gyymrljl2wjl4zh3rqefeqsnyjj0
  - path_regex: 'hosts/ms/dome/happy-owl/secrets/[^/]+\.yaml$'
    key_groups:
      - age:
        - age1c9xuldm8rxssv00a0y9zav0fcjzujtqgtv2t0gkk4anutvuz3s3qry70pm
        - age1revy59xnwzqfukcukjqcu76kz7vflmncme4h4gykw7afv8wz4gvsydm3sp
        - age1ud74hwzecx9tk2wk07l232tdd63hkcx58w7u0dq7f0r5748s4f5qvuw3cg
