# Managed by setup_new_machine.sh.
keys:
  admins:
    - age1c9xuldm8rxssv00a0y9zav0fcjzujtqgtv2t0gkk4anutvuz3s3qry70pm
  hosts:
    - fqdn: node1.dome.ms
      age: age15pvv0wmfmt8mq7nr2v8uek2zypzgscv4jev4wm86vr6e94xkga9qvdt4tk
      path_regex: 'hosts/ms/dome/node1/secrets/[^/]+\.yaml$'
creation_rules:
  - path_regex: 'secrets/cluster\.yaml$'
    key_groups:
      - age:
        - age1c9xuldm8rxssv00a0y9zav0fcjzujtqgtv2t0gkk4anutvuz3s3qry70pm
        - age15pvv0wmfmt8mq7nr2v8uek2zypzgscv4jev4wm86vr6e94xkga9qvdt4tk
  - path_regex: 'hosts/ms/dome/node1/secrets/[^/]+\.yaml$'
    key_groups:
      - age:
        - age1c9xuldm8rxssv00a0y9zav0fcjzujtqgtv2t0gkk4anutvuz3s3qry70pm
        - age15pvv0wmfmt8mq7nr2v8uek2zypzgscv4jev4wm86vr6e94xkga9qvdt4tk
